version: '3'
services:
  influxdb:
    image: "influxdb:1.6.3"
    env_file:
      - .env
    ports:
      - "8086:8086"
      - "8082:8082"
      - "8089:8089"

  telegraf:
    image: "telegraf:1.6.3"
    env_file:
      - .env
    environment:
      HOSTNAME: "telegraf-getting-started"
    links:
      - influxdb
    volumes:
      - ./telegraf/:/etc/telegraf/
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - influxdb

  chronograf:
    image: "chronograf:1.6.2"
    env_file:
      - .env
    environment:
      RESOURCES_PATH: "/usr/share/chronograf/resources"
    links:
      - influxdb
    ports:
      - "8888:8888"
    depends_on:
      - influxdb
      - telegraf

